class ReportService:

    def generate(
        self,
        workers,
        stats,
        missing,
        score,
        risk,
    ):

        if risk == "LOW":

            summary = (
                "The workplace is operating with good PPE compliance. "
                "Most workers are wearing the required protective equipment."
            )

        elif risk == "MEDIUM":

            summary = (
                "Several PPE violations were detected. "
                "Immediate corrective action is recommended to improve safety."
            )

        else:

            summary = (
                "Critical PPE violations were detected. "
                "Immediate intervention is required to protect workers."
            )

        report = f"""
VisionDesk AI Workplace Safety Inspection Report

------------------------------------------------

Workers Detected : {workers}

Safety Score : {score}%

Risk Level : {risk}

------------------------------------------------

Detected PPE

Helmet : {stats["helmet"]}

Vest : {stats["vest"]}

Gloves : {stats["gloves"]}

Goggles : {stats["goggles"]}

Boots : {stats["boots"]}

------------------------------------------------

Missing PPE

Helmet : {missing["helmet"]}

Vest : {missing["vest"]}

Gloves : {missing["gloves"]}

Goggles : {missing["goggles"]}

Boots : {missing["boots"]}

------------------------------------------------

Overall Summary

{summary}

------------------------------------------------

Recommendations

• Ensure every worker wears complete PPE.

• Replace all missing protective equipment.

• Conduct PPE inspections before every shift.

• Improve worker safety awareness.

• Continue monitoring using VisionDesk AI.

------------------------------------------------

Generated by VisionDesk AI
"""

        return report


report_service = ReportService()